# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-23 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    def combine_names(apps, schema_editor):
        # We can't import the Person model directly as it may be a newer
        # version than this migration expects. We use the historical version.
        Site = apps.get_model('sculpture', 'Site')
        for site in Site.objects.all():
            names = ''
            for a in site.authors.all():
                if names == '':
                    names = a.name
                else:
                    names = '{}; {}'.format(names, a.name)
            site.fieldworker_may_2017 = names
            site.save()


    dependencies = [
        ('sculpture', '0002_auto_20180116_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='fieldworker_may_2017',
            field=models.CharField(blank=True, help_text='Fieldworkers as of May 2017', max_length=2048, verbose_name='May 2017 Fieldworkers'),
        ),

        migrations.RunPython(combine_names),
    ]
