# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-06 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sculpture', '0005_image_copyright_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='sites', to='sculpture.Contributor'),
        ),
        migrations.AlterField(
            model_name='site',
            name='dedications',
            field=models.ManyToManyField(blank=True, related_name='sites', through='sculpture.SiteDedication', to='sculpture.Dedication'),
        ),
        migrations.AlterField(
            model_name='site',
            name='dioceses',
            field=models.ManyToManyField(blank=True, related_name='sites', through='sculpture.SiteDiocese', to='sculpture.Diocese'),
        ),
        migrations.AlterField(
            model_name='site',
            name='glossary_terms',
            field=models.ManyToManyField(blank=True, editable=False, related_name='sites', to='sculpture.GlossaryTerm'),
        ),
        migrations.AlterField(
            model_name='site',
            name='regions',
            field=models.ManyToManyField(blank=True, related_name='sites', through='sculpture.SiteRegion', to='sculpture.Region'),
        ),
    ]
