# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-01 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sculpture', '0006_auto_20180406_1521'),
    ]

    def save_all(apps, schema_editor):
        # We can't import the Person model directly as it may be a newer
        # version than this migration expects. We use the historical version.
        Site = apps.get_model('sculpture', 'Site')
        for site in Site.objects.all():
            site.save()

    operations = [
        migrations.AddField(
            model_name='site',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),

        migrations.RunPython(save_all),
    ]
