# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-12 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sculpture', '0007_site_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='fieldworker_may_2017',
            field=models.CharField(blank=True, help_text='Fieldworkers as of May 2018', max_length=2048, verbose_name='May 2018 Fieldworkers'),
        ),
    ]
