# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-28 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sculpture', '0008_auto_20180612_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureimage',
            name='height',
            field=models.IntegerField(blank=True, help_text='Height in pixels.'),
        ),
        migrations.AlterField(
            model_name='featureimage',
            name='status',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sculpture_featureimage_images', to='sculpture.ImageStatus'),
        ),
        migrations.AlterField(
            model_name='featureimage',
            name='width',
            field=models.IntegerField(blank=True, help_text='Width in pixels.'),
        ),
        migrations.AlterField(
            model_name='siteimage',
            name='height',
            field=models.IntegerField(blank=True, help_text='Height in pixels.'),
        ),
        migrations.AlterField(
            model_name='siteimage',
            name='status',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sculpture_siteimage_images', to='sculpture.ImageStatus'),
        ),
        migrations.AlterField(
            model_name='siteimage',
            name='width',
            field=models.IntegerField(blank=True, help_text='Width in pixels.'),
        ),
    ]
